version: '2.3'

services:
  face_recognition:
    build: 
      context: ./
    image: face_recognition
    container_name: face_recognition
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video0:/dev/video0
